version: "3"

services:
  #  nginx:
  #    build: ./docker/nginx
  #    depends_on:
  #      - php
  #      - node
  #    networks:
  #      - app-tier
  #    ports:
  #      - '127.0.0.1:8080:80'
  #      - '443:443'
  #    volumes:
  #      - .:/app:cached
  #      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf

  php:
    build: ./docker/php
    networks:
      - app
    volumes:
      - .:/app:cached
    depends_on:
      - db
    links:
      - db
    ports:
      - "127.0.0.1:8000:8000"

  db:
    image: postgres:${POSTGRES_VERSION}-alpine
#    restart:
    networks:
      - app
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${DATABASE_PORT}:5432"
    volumes:
      -   db:/var/lib/mysql

networks:
  app:

volumes:
  db:
