version: "3"

services:
  nginx:
    image: nginx:1.23.4
    restart: ${RESTART}
    depends_on:
      - php
      - db
    networks:
      - app
    ports:
      - '${NGINX_PORT}:80'
    environment:
      - NGINX_HOST=${NGINX_HOST}
      - NGINX_PORT=${NGINX_PORT}
    volumes:
      - .:/app
      - ./docker/nginx/default.conf.template:/etc/nginx/templates/default.conf.template

  php:
    build: ./docker/php
    restart: ${RESTART}
    networks:
      - app
    volumes:
      - .:/app
    depends_on:
      - db
    links:
      - db

  db:
    image: postgres:${POSTGRES_VERSION}-alpine
    restart: ${RESTART}
    networks:
      - app
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - '${DATABASE_PORT}:5432'
    volumes:
      -   db:/var/lib/postgresql/data

networks:
  app:

volumes:
  db:
